markdown: kramdown
url: https://nodeontrain.xyz
enforce_ssl: nodeontrain.xyz
highlighter: rouge
relative_permalinks: false
permalink: /news/:year/:month/:day/:title
gems:
  - jekyll-sitemap
exclude:
  - vendor
